version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1
      - image: mysql:5.7
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - APP_KEY: tX0quMU3+TwtR0xuU/rXD5UKMzd66mmu0C5QQplLCJ0=
          - DB_CONNECTION: circle_test
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/coachtech-advanced-ec-site
    steps:
      - checkout:
          path: ~/coachtech-advanced-ec-site
      - run:
          name: Install PHP dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y libpq-dev unzip
            composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - run:
          name: Install Node.js dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm install

  test:
    docker:
      - image: cimg/php:8.1
      - image: mysql:5.7
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - APP_KEY: tX0quMU3+TwtR0xuU/rXD5UKMzd66mmu0C5QQplLCJ0=
          - DB_CONNECTION: circle_test
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/coachtech-advanced-ec-site
    steps:
      - checkout:
          path: ~/coachtech-advanced-ec-site
      - run:
          name: Install PHP dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y libpq-dev unzip
            composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - run:
          name: Install Node.js dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm install
      - run:
          name: Run tests
          command: vendor/bin/phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build




